controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

messages:
    path: /messages
    controller: App\Controller\MessageController::newMessage
    methods: [POST]

api_login_check:
    path: /api/login_check
    methods: POST


